### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by hanigamini** [cedarstudios/cedarmaps-nodejs-client#1]
با سلام آیا سدار از مپ باکس استفاده میکنه؟
موقع نصب این پیغام را بهم داد.

npm install cedar-maps

+-- cedar-maps@2.0.1
| `-- query-string@6.1.0
|   `-- strict-uri-encode@2.0.0
`-- UNMET PEER DEPENDENCY mapbox-gl@0.47.0 extraneous

npm WARN @mapbox/mapbox-gl-directions@3.1.3 requires a peer of mapbox-gl@^0.41.0 but none was installed.

و یه سوال دیگه اینکه آیا نمونه کد نود هم برای سدار دارید؟
من مبدا و مقصد را دارم و میخوام فاصله زمانی و مسافت مسیر را در بیارم.
Lat و lng را دارم.
آیا کد زیر درسته؟

 const cedarMaps = require('cedar-maps');
    const apiKey = api_key;
    const CedarMaps = cedarMaps(apiKey);
    CedarMaps.distance({ lat: sourceLat, lon: sourceLon }, { lat: destinationLat, lon: destinationLon });

**Comment by mohsentaleb** [comment]
@hanigamini مستندات این پکیج آپدیت شد و نمونه کدهای لازم در آن قرار داده شده. لطفا مطالعه بفرمایید: 
https://github.com/cedarstudios/cedarmaps-nodejs-client#trip-calculator
